[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["development-tools::testing", "gui"]
description = "Testing library for relm"
documentation = "https://docs.rs/relm-test/"
license = "MIT"
name = "relm-test"
repository = "https://github.com/antoyo/relm"
version = "0.14.4"

[dependencies]
gdk = "^0.8.0"
gdk-sys = "^0.6.0"
glib = "^0.5.0"
glib-sys = "^0.6.0"
gtk = "^0.4.0"
gtk-sys = "^0.6.0"

[dependencies.relm-core]
path = "../relm-core"
version = "^0.14.0"
